name: CIs on pull requests

on: pull_request

jobs:
  path-filter: # Get changed files to filter jobs
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions: {}
    outputs:
      lint-actions: ${{steps.changes.outputs.lint-actions}}
    steps:
      - uses: dorny/paths-filter@0e4a8c6effa4802afeda77dc8d303f8176d7dfad # v3.0.4
        id: changes
        with:
          filters: |
            lint-actions:
              - .github/workflows/*
              - aqua.yaml
              - .github/ghalint.yml
              - .github/pinact.yml

  status-check: # for Rulesets/main
    runs-on: ubuntu-latest
    if: failure()
    timeout-minutes: 10
    permissions: {}
    needs:
      - lint-actions
    steps:
      - run: exit 1

  #
  # main CIs
  #

  lint-actions:
    needs: path-filter
    if: needs.path-filter.outputs.lint-actions == 'true'
    uses: ./.github/workflows/wc-lint-actions.yml
    permissions:
      contents: read
      pull-requests: write
    with:
      pinact-skip-push: true
