name: add labels based on .github/labeler.yml

on:
  workflow_call:
    inputs: {}
    secrets:
      APP_ID:
        description: the ID of GitHub App with the role of tag push 
        required: true
      APP_PRIVATE_KEY:
        description: the private key of GitHub App with the role of tag push 
        required: true

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      # to trigger other Actions caused by adding reviewapp Label
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-pull-requests: write

      - id: label-the-PR
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          repo-token: ${{ steps.app-token.outputs.token }}
