name: run common linters for GitHub Action

on:
  workflow_call:
    inputs: {}
    secrets:
      APP_ID:
        description: the ID of GitHub App with the role of tag push 
        required: true
      APP_PRIVATE_KEY:
        description: the private key of GitHub App with the role of tag push 
        required: true

jobs:
  actionlint:
    name: actionlint with reviewdog
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: actionlint
        uses: reviewdog/action-actionlint@a5524e1c19e62881d79c1f1b9b6f09f16356e281 # v1.65.2
        with:
          reporter: github-pr-review

  pinact:
    name: run pinact and push new commit if needed
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: suzuki-shunsuke/pinact-action@5c5491051b56f602db279fe380abaf4112727eb2 # v0.2.2
        with:
          app_id: ${{secrets.APP_ID}}
          app_private_key: ${{secrets.APP_PRIVATE_KEY}}
