name: cleanup ECS manifests for Review Apps

on:
  workflow_call:
    inputs:
      prefix:
        description: the prefix name of the cleanup target in reviewapps directory (e.g. dk-)
        type: string
      aws_region:
        type: string
        default: us-west-2
    secrets:
      APP_ID:
        description: the ID of GitHub App with the role that pull/push to dreamkast-infra
        required: true
      APP_PRIVATE_KEY:
        description: the private key of GitHub App with the role that pull/push to dreamkast-infra
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

# this workflow should not work with cleanup workflow
concurrency: reviewapps

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 10
    steps:
      - name: Set current unixtime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "UNIXTIME=$(date +'+%s')" >> "$GITHUB_ENV"

      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: cloudnativedaysjp
          repositories: dreamkast-infra
          permission-contents: write
          permission-pull-requests: write

      - name: Install ecspresso
        uses: kayac/ecspresso@b4cc24aaeba4216ecd80632953f2b9db51e8489c # v2

      - name: Checkout dreamkast-infra
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          repository: cloudnativedaysjp/dreamkast-infra

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Cleanup
        working-directory: ecspresso/reviewapps
        env:
          GH_TOKEN: ${{ github.token }}
          PREFIX: ${{ inputs.prefix }}
        shell: bash -xe {0}
        run: |
          EXPECTED="$(gh pr list --repo ${{ github.repository }} --label 'reviewapps' --json number --jq '.[].number' | sed 's/^\(.*\)$/'"$PREFIX"'\1/g')"
          # shellcheck disable=SC2010,SC2086
          ACTUAL="$(ls | grep -E ^$PREFIX ||:)"

          # If present only in ACTUAL, cleanup
          for act in $ACTUAL; do
            EXIST=false
            for exp in $EXPECTED; do
              [ "$act" = "$exp" ] && EXIST=true
            done
            [ "$EXIST" = "true" ] && continue
            bash -x "$act/cleanup.sh"
            rm -rf "$act"
          done

      - name: check diff
        id: check-diff
        run: |
          git add . --intent-to-add
          if git diff --exit-code --quiet HEAD --; then
            echo "changes=false" >> "$GITHUB_OUTPUT"
          else
            echo "changes=true" >> "$GITHUB_OUTPUT"
          fi

      # TODO(kanata): investigate the issue that suzuki-shunsuke/commit-action didn't commit delete files
      #- name: Commit files
      #  if: steps.check-diff.outputs.changes == 'true'
      #  uses: suzuki-shunsuke/commit-action@cc96d3a3fd959d05e9b79ca395eb30b835aeba24 # v0.0.7
      #  with:
      #    repository: cloudnativedaysjp/dreamkast-infra
      #    branch: gitops/reviewapps/${{ github.repository }}/${{ env.UNIXTIME }}
      #    github_token: ${{ steps.app-token.outputs.token }}
      #    commit_message: |
      #      cleanup ReviewApps by GHA in ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}
      #      action URL: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}

      - name: Commit files
        if: steps.check-diff.outputs.changes == 'true'
        run: |
          APP_USER_ID=$(curl -sSL --globoff "https://api.github.com/users/${{ steps.app-token.outputs.app-slug }}[bot]" | jq -r .id)
          git config --local user.name "${{ steps.app-token.outputs.app-slug }}[bot]"
          git config --local user.email "${APP_USER_ID}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"
          git status
          git add -A
          git commit -a -F- <<EOM
          cleanup ReviewApps by GHA in ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}
          action URL: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
          EOM

      - name: Push changes
        if: steps.check-diff.outputs.changes == 'true'
        uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df # v0.8.0
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          repository: cloudnativedaysjp/dreamkast-infra
          directory: dreamkast-infra
          branch: "gitops/reviewapps/${{ github.repository }}/${{ env.UNIXTIME }}"

      - name: Create and Merge Pull Request
        if: steps.check-diff.outputs.changes == 'true'
        uses: "actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea" # v7.0.1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const pr = await github.rest.pulls.create({
              owner: "cloudnativedaysjp",
              repo: "dreamkast-infra",
              title: "Automated PR (gitops/reviewapps/${{ github.repository }})",
              body: "**this PR is automatically created & merged**",
              head: "gitops/reviewapps/${{ github.repository }}/${{ env.UNIXTIME }}",
              base: "main"
            });
            await github.rest.pulls.merge({
              owner: "cloudnativedaysjp",
              repo: "dreamkast-infra",
              pull_number: pr.data.number,
              merge_method: "squash",
            });
