name: Push a new tag when Pull Requests are merged

on:
  workflow_call:
    inputs: {}
    secrets:
      APP_ID:
        description: the ID of GitHub App with the role of tag push 
        required: true
      APP_PRIVATE_KEY:
        description: the private key of GitHub App with the role of tag push 
        required: true

jobs:
  tagging:
    if: ${{ github.event.pull_request.state == 'closed' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    timeout-minutes: 3
    steps:
      # to trigger other Actions caused by adding reviewapp Label
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # TODO: stop using actions-ecosystem in order to set persist-credentials to false
          persist-credentials: true
          token: ${{ steps.app-token.outputs.token }}

      - uses: actions-ecosystem/action-release-label@1c7ef83d383a57bf253a2e2e9dfe1b55f445ae15 # v1.2.0
        id: release-label
        if: ${{ github.event.pull_request.merged == true }}

      - uses: actions-ecosystem/action-get-latest-tag@b7c32daec3395a9616f88548363a42652b22d435 # v1.6.0
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}

      - uses: actions-ecosystem/action-bump-semver@34e334551143a5301f38c830e44a22273c6ff5c5 # v1.0.0
        id: bump-semver
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}

      - uses: actions-ecosystem/action-push-tag@6e82caefe706f5a729e354df7443dc82f98a414f # v1.0.0
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'

      - uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 # v2.9.1
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          number: ${{ github.event.number }}
          message: |
            ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/tag/${{ steps.bump-semver.outputs.new_version }} will be released.
